# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Release SDK

on:
  workflow_dispatch:
    inputs:
      javascript-release:
        required: false
        type: boolean
        description: 'Make a javascript SDK release.'
        default: false
      python-release:
        required: false
        type: boolean
        description: 'Make a python SDK release.'
        default: false

  workflow_call:
    inputs:
      javascript-release:
        required: false
        type: boolean
        description: 'Make a javascript SDK release.'
        default: false
      python-release:
        required: false
        type: boolean
        description: 'Make a python SDK release.'
        default: false
    secrets:
      NPMJS_TOKEN:
        required: true
      PYPI_API_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  python:
    name: Python
    if: ${{ inputs.python-release == true || inputs.python-release == 'true' }}
    runs-on: ubuntu-latest
    env:
      UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Taskfile
        shell: bash
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Install deps
        shell: bash
        run: |
          task deps

      - name: Build the Python package
        run: |
          task sdk:build:python

      - name: Publish the Python SDK
        run: |
          task sdk:release:python

  javascript:
    name: JavaScript
    if: ${{ inputs.javascript-release == true || inputs.javascript-release == 'true' }}
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Taskfile
        shell: bash
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '24.x'
          registry-url: https://registry.npmjs.org/
          scope: '@agntcy'

      - name: Install deps
        shell: bash
        run: |
          task deps

      - name: Build the Javascript package
        run: |
          task sdk:deps:javascript
          task sdk:build:javascript

      - name: Publish the Javascript SDK
        run: |
          task sdk:release:javascript
